from __future__ import annotations

import tkinter as tk
import threading
import os
import subprocess
import sys
from datetime import datetime
from pathlib import Path
from tkinter import filedialog, messagebox, ttk

from .config import load_configuration, save_configuration
from .chrome_bridge import probe_whatsapp_chrome
from .models import MONTH_NAMES, MONTH_NUMBERS, AppConfiguration, PeriodSelection
from .label_parser import LabelDraft
from .grouping_service import ConsolidatedRow, group_approved_drafts
from .review_service import build_review_drafts
from .workbook_writer_service import write_approved_rows
from .stake_parser import parse_stake_text
from .whatsapp_service import WhatsAppProbeResult
from .workbook_service import validate_workbook


COLORS = {
    "navy": "#17365D",
    "blue": "#2F75B5",
    "light_blue": "#D9EAF7",
    "green": "#2E7D32",
    "light_green": "#E2F0D9",
    "amber": "#9C6500",
    "light_amber": "#FFF2CC",
    "red": "#9C0006",
    "light_red": "#FCE4D6",
    "background": "#F4F7FA",
    "card": "#FFFFFF",
    "text": "#1F2937",
    "muted": "#667085",
    "border": "#D0D5DD",
}


class FechamentoApp(tk.Tk):
    def __init__(self) -> None:
        super().__init__()
        self.title("Automação do Fechamento WL")
        self.geometry("1040x610+35+25")
        self.minsize(900, 550)
        self.configure(bg=COLORS["background"])

        self.config_data = load_configuration()
        self.workbook_var = tk.StringVar(value=self.config_data.workbook_path)
        self.month_var = tk.StringVar(
            value=MONTH_NAMES.get(self.config_data.last_month, "julho")
        )
        self.year_var = tk.StringVar(value=str(self.config_data.last_year))
        self.fortnight_var = tk.IntVar(value=self.config_data.last_fortnight)
        self.period_var = tk.StringVar(value="Selecione o período para validar.")
        self.status_var = tk.StringVar(value="Aguardando configuração")
        self.stake_input_var = tk.StringVar(value="16x10=600")
        self.stake_result_var = tk.StringVar(value="")
        self.last_whatsapp_result: WhatsAppProbeResult | None = None
        # Reuse the single canonical review generated by the integrated app.
        # This lets the user reopen an existing corrected review after
        # restarting the application instead of starting an empty OCR run.
        canonical_review = Path(r"C:\Users\lilia\Downloads\FECHAMENTOS PRELOG\Revisão Fechamento WL\revisao_temporaria.html")
        fallback_review = Path(__file__).resolve().parents[1] / "runtime_captures" / "revisao_live_2026-08" / "revisao_temporaria.html"
        self.review_html_path: Path | None = next(
            (path for path in (canonical_review, fallback_review) if path.exists()),
            None,
        )

        self._build_styles()
        self._build_layout()
        if self.review_html_path is not None:
            self.review_button.configure(state="normal", text="Abrir revisão temporária")
        self._update_period_preview()

    def _build_styles(self) -> None:
        style = ttk.Style(self)
        style.theme_use("clam")
        style.configure(
            "TCombobox",
            padding=8,
            fieldbackground="white",
            bordercolor=COLORS["border"],
        )
        style.configure("TSpinbox", padding=8)
        style.configure(
            "Primary.TButton",
            background=COLORS["blue"],
            foreground="white",
            borderwidth=0,
            padding=(18, 11),
            font=("Segoe UI", 10, "bold"),
        )
        style.map("Primary.TButton", background=[("active", "#245E91")])
        style.configure(
            "Secondary.TButton",
            background="white",
            foreground=COLORS["navy"],
            bordercolor=COLORS["border"],
            padding=(14, 9),
            font=("Segoe UI", 10),
        )
        style.configure("TRadiobutton", background=COLORS["card"], font=("Segoe UI", 10))

    def _build_layout(self) -> None:
        header = tk.Frame(self, bg=COLORS["navy"], height=62)
        header.pack(fill="x")
        header.pack_propagate(False)
        tk.Label(
            header,
            text="Automação do Fechamento WL",
            bg=COLORS["navy"],
            fg="white",
            font=("Segoe UI", 20, "bold"),
        ).pack(anchor="w", padx=34, pady=(10, 0))

        body = tk.Frame(self, bg=COLORS["background"])
        body.pack(fill="both", expand=True, padx=28, pady=10)
        body.grid_columnconfigure(0, weight=3)
        body.grid_columnconfigure(1, weight=2)
        body.grid_rowconfigure(0, weight=1)

        left = tk.Frame(body, bg=COLORS["card"], highlightbackground=COLORS["border"], highlightthickness=1)
        left.grid(row=0, column=0, sticky="nsew", padx=(0, 16))
        right = tk.Frame(body, bg=COLORS["card"], highlightbackground=COLORS["border"], highlightthickness=1)
        right.grid(row=0, column=1, sticky="nsew")

        self._build_configuration_card(left)
        self._build_status_card(right)

    def _section_title(self, parent: tk.Widget, title: str, subtitle: str) -> None:
        tk.Label(parent, text=title, bg=COLORS["card"], fg=COLORS["text"], font=("Segoe UI", 15, "bold")).pack(anchor="w")
        tk.Label(
            parent,
            text=subtitle,
            bg=COLORS["card"],
            fg=COLORS["muted"],
            font=("Segoe UI", 9),
            anchor="w",
            justify="left",
        ).pack(fill="x", anchor="w", pady=(2, 8))

    def _build_configuration_card(self, parent: tk.Frame) -> None:
        content = tk.Frame(parent, bg=COLORS["card"])
        content.pack(fill="both", expand=True, padx=24, pady=12)
        self._section_title(
            content,
            "Preparar fechamento",
            "Escolha a planilha oficial e o período.\nEsta etapa apenas valida; nenhum dado será escrito.",
        )

        tk.Label(content, text="Planilha oficial", bg=COLORS["card"], fg=COLORS["text"], font=("Segoe UI", 10, "bold")).pack(anchor="w")
        file_row = tk.Frame(content, bg=COLORS["card"])
        file_row.pack(fill="x", pady=(5, 9))
        entry = tk.Entry(file_row, textvariable=self.workbook_var, relief="solid", bd=1, fg=COLORS["text"], readonlybackground="white", font=("Segoe UI", 9), state="readonly")
        entry.pack(side="left", fill="x", expand=True, ipady=9)
        ttk.Button(file_row, text="Escolher arquivo", style="Secondary.TButton", command=self._choose_workbook).pack(side="left", padx=(10, 0))

        tk.Label(content, text="Período", bg=COLORS["card"], fg=COLORS["text"], font=("Segoe UI", 10, "bold")).pack(anchor="w")
        period_row = tk.Frame(content, bg=COLORS["card"])
        period_row.pack(fill="x", pady=(7, 10))

        month_combo = ttk.Combobox(period_row, textvariable=self.month_var, values=list(MONTH_NAMES.values()), state="readonly", width=18)
        month_combo.pack(side="left", padx=(0, 10))
        month_combo.bind("<<ComboboxSelected>>", lambda _event: self._update_period_preview())

        year_spin = ttk.Spinbox(period_row, from_=2020, to=2100, textvariable=self.year_var, width=9, command=self._update_period_preview)
        year_spin.pack(side="left")
        year_spin.bind("<FocusOut>", lambda _event: self._update_period_preview())
        year_spin.bind("<KeyRelease>", lambda _event: self._update_period_preview())

        fortnight_box = tk.Frame(content, bg=COLORS["card"])
        fortnight_box.pack(fill="x", pady=(3, 11))
        ttk.Radiobutton(fortnight_box, text="1ª quinzena (dias 1 a 15)", variable=self.fortnight_var, value=1, command=self._update_period_preview).pack(side="left")
        ttk.Radiobutton(fortnight_box, text="2ª quinzena (dia 16 ao fim)", variable=self.fortnight_var, value=2, command=self._update_period_preview).pack(side="left", padx=(22, 0))

        preview = tk.Label(content, textvariable=self.period_var, bg=COLORS["light_blue"], fg=COLORS["navy"], font=("Segoe UI", 10, "bold"), anchor="w", padx=13, pady=11)
        preview.pack(fill="x", pady=(0, 10))

        ttk.Button(content, text="Validar planilha e período", style="Primary.TButton", command=self._validate_selection).pack(anchor="w")

        separator = ttk.Separator(content, orient="horizontal")
        separator.pack(fill="x", pady=12)

        tk.Label(content, text="Teste da nova entrada de Estaca", bg=COLORS["card"], fg=COLORS["text"], font=("Segoe UI", 11, "bold")).pack(anchor="w")
        tk.Label(content, text="Confirma a regra textual antes da integração com o WhatsApp.", bg=COLORS["card"], fg=COLORS["muted"], font=("Segoe UI", 9)).pack(anchor="w", pady=(2, 8))
        stake_row = tk.Frame(content, bg=COLORS["card"])
        stake_row.pack(fill="x")
        tk.Entry(stake_row, textvariable=self.stake_input_var, relief="solid", bd=1, font=("Segoe UI", 10)).pack(side="left", fill="x", expand=True, ipady=8)
        ttk.Button(stake_row, text="Calcular", style="Secondary.TButton", command=self._test_stake_entry).pack(side="left", padx=(10, 0))
        tk.Label(content, textvariable=self.stake_result_var, bg=COLORS["card"], fg=COLORS["green"], font=("Segoe UI", 9, "bold"), wraplength=590, justify="left").pack(anchor="w", pady=(9, 0))

    def _build_status_card(self, parent: tk.Frame) -> None:
        content = tk.Frame(parent, bg=COLORS["card"])
        content.pack(fill="both", expand=True, padx=22, pady=12)
        self._section_title(content, "Situação do piloto", "A configuração precisa estar válida antes da leitura do WhatsApp.")

        self.status_banner = tk.Label(content, textvariable=self.status_var, bg=COLORS["light_amber"], fg=COLORS["amber"], font=("Segoe UI", 12, "bold"), anchor="w", padx=14, pady=14)
        self.status_banner.pack(fill="x")

        tk.Label(content, text="Verificações", bg=COLORS["card"], fg=COLORS["text"], font=("Segoe UI", 10, "bold")).pack(anchor="w", pady=(15, 7))
        self.details_text = tk.Text(content, height=17, wrap="word", relief="flat", bg="#F9FAFB", fg=COLORS["text"], font=("Segoe UI", 9), padx=12, pady=12, state="disabled")
        self.details_text.pack(fill="both", expand=True)
        self._set_details([
            "• Selecione a planilha oficial.",
            "• Escolha o mês, ano e quinzena.",
            "• Clique em Validar planilha e período.",
            "",
            "A validação é somente leitura e não modifica o arquivo.",
        ])

        self.next_button = ttk.Button(
            content,
            text="Ler evidências da quinzena",
            style="Secondary.TButton",
            state="disabled",
            command=self._start_whatsapp_probe,
        )
        self.next_button.pack(fill="x", pady=(12, 0))
        self.review_button = ttk.Button(
            content,
            text="Analisar fotos e abrir revisão temporária",
            style="Primary.TButton",
            state="disabled",
            command=self._start_photo_review,
        )
        self.review_button.pack(fill="x", pady=(8, 0))

    def _choose_workbook(self) -> None:
        initial = Path(self.workbook_var.get()).parent if self.workbook_var.get() else Path.home()
        selected = filedialog.askopenfilename(
            title="Escolha a planilha oficial",
            initialdir=str(initial),
            filetypes=[("Planilhas Excel", "*.xlsx *.xlsm"), ("Todos os arquivos", "*.*")],
        )
        if selected:
            self.workbook_var.set(selected)
            self.status_var.set("Arquivo selecionado; falta validar")
            self._set_status("warning")

    def _period(self) -> PeriodSelection:
        month = MONTH_NUMBERS[self.month_var.get()]
        return PeriodSelection(
            year=int(self.year_var.get()),
            month=month,
            fortnight=int(self.fortnight_var.get()),
        )

    def _update_period_preview(self) -> None:
        try:
            period = self._period()
            self.period_var.set(f"{period.label}  •  Aba esperada: {period.sheet_name}")
        except (ValueError, KeyError):
            self.period_var.set("Informe um mês, ano e quinzena válidos.")

    def _validate_selection(self) -> None:
        workbook_path = self.workbook_var.get().strip()
        if not workbook_path:
            messagebox.showwarning("Planilha necessária", "Escolha a planilha oficial antes de validar.")
            return
        try:
            period = self._period()
        except (ValueError, KeyError) as exc:
            messagebox.showwarning("Período inválido", str(exc))
            return

        self.status_var.set("Validando planilha…")
        self.update_idletasks()
        result = validate_workbook(workbook_path, period)
        details = list(result.messages)
        details.append("")
        details.append(f"Arquivo: {result.path.name}")
        details.append(f"Período: {period.label}")
        details.append(f"Aba: {period.sheet_name}")

        if result.valid:
            self.config_data = AppConfiguration(
                workbook_path=str(result.path),
                last_year=period.year,
                last_month=period.month,
                last_fortnight=period.fortnight,
            )
            save_configuration(self.config_data)
            self.status_var.set("Configuração válida")
            self._set_status("success")
            self.next_button.configure(state="normal")
            details.append("")
            details.append("✓ Localização memorizada para a próxima execução.")
            details.append("✓ Nenhuma célula foi modificada.")
        else:
            self.status_var.set("Configuração precisa de correção")
            self._set_status("error")
            self.next_button.configure(state="disabled")
            details.append("")
            details.append("A planilha não foi configurada. Corrija os itens acima.")
        self._set_details(details)

    def _start_whatsapp_probe(self) -> None:
        try:
            period = self._period()
        except (ValueError, KeyError) as exc:
            messagebox.showwarning("Período inválido", str(exc))
            return

        self.next_button.configure(state="disabled")
        self.status_var.set("Conectando ao WhatsApp…")
        self._set_status("warning")
        self._set_details([
            "• Grupo: AWL x Expedição Prellog",
            f"• Data inicial procurada: {period.start_date.strftime('%d/%m/%Y')}",
            "• Use somente uma aba do WhatsApp Web no perfil AWL.",
            "• Deixe o grupo aberto nessa aba antes de iniciar.",
            "• A extensão instalada fará a leitura somente do WhatsApp Web.",
            "",
            "Este teste não reage, não envia mensagens e não altera a planilha.",
        ])

        worker = threading.Thread(
            target=self._run_whatsapp_probe,
            args=(period,),
            daemon=True,
        )
        worker.start()

    def _run_whatsapp_probe(self, period: PeriodSelection) -> None:
        try:
            result = probe_whatsapp_chrome(period.start_date, period.end_date)
        except Exception as exc:
            message = str(exc)
            self.after(0, lambda: self._show_whatsapp_error(message))
            return
        self.after(0, lambda: self._show_whatsapp_result(result))

    def _show_whatsapp_error(self, message: str) -> None:
        self.status_var.set("WhatsApp não conectado")
        self._set_status("error")
        self._set_details([
            "• Não foi possível concluir o teste.",
            f"• Motivo: {message}",
            "",
            "Nenhuma mensagem e nenhum dado da planilha foram alterados.",
        ])
        self.next_button.configure(state="normal")

    def _show_whatsapp_result(self, result: WhatsAppProbeResult) -> None:
        self.last_whatsapp_result = result
        if result.start_date_found:
            self.status_var.set(
                "Período e evidências lidos"
                if result.evidences
                else "WhatsApp e período comprovados"
            )
            self._set_status("success")
        elif result.sync_in_progress:
            self.status_var.set("WhatsApp ainda está sincronizando")
            self._set_status("warning")
        else:
            self.status_var.set("WhatsApp conectado; histórico incompleto")
            self._set_status("warning")

        stake_text = (
            ", ".join(result.stake_messages)
            if result.stake_messages
            else "nenhuma visível"
        )
        evidence_lines = []
        for evidence in result.evidences[:8]:
            sender = f" • {evidence.sender}" if evidence.sender else ""
            evidence_lines.append(
                f"  {evidence.message_date} {evidence.message_time}{sender} • "
                f"{evidence.kind_label}"
            )
        if len(result.evidences) > 8:
            evidence_lines.append(
                f"  … e mais {len(result.evidences) - 8} mensagens no inventário."
            )
        if result.evidence_truncated:
            evidence_lines.append("  ⚠ O inventário atingiu o limite de segurança.")

        details = [
            f"• Conexão: {'OK' if result.connected else 'não'}",
            f"• Grupo correto: {'OK' if result.group_found else 'não encontrado'}",
            (
                f"• Data inicial {result.start_date}: "
                f"{'encontrada' if result.start_date_found else 'não encontrada'}"
            ),
            f"• Etapas de carregamento: {result.load_attempts}",
            f"• Esperas pela sincronização: {result.sync_waits}",
            (
                "• Sincronização do celular: "
                f"{'em andamento' if result.sync_in_progress else 'concluída'}"
            ),
            f"• Fotos visíveis: {result.visible_images}",
            f"• Fotos copiadas com segurança: {len(result.captured_attachments)}",
            f"• Álbuns ainda incompletos: {len(result.incomplete_albums)}",
            f"• PDFs visíveis: {result.visible_pdfs}",
            f"• Entradas de Estaca visíveis: {stake_text}",
            f"• Mensagens com evidência no período: {len(result.evidences)}",
            "",
            "Inventário (primeiras mensagens):",
            *(evidence_lines or ["  Nenhuma evidência estruturada foi encontrada."]),
            "",
            result.message,
            "Nenhuma mensagem e nenhum dado da planilha foram alterados.",
        ]
        self._set_details(details)
        self.next_button.configure(state="normal", text="Atualizar leitura das evidências")
        if result.captured_attachments:
            self.review_button.configure(state="normal")
            # Open the temporary review automatically when the read produced
            # period evidence; the button remains available for reopening it.
            if result.evidences:
                self.after(350, self._start_photo_review)

    def _start_photo_review(self) -> None:
        if self.review_html_path and self.review_html_path.exists():
            os.startfile(str(self.review_html_path))
            return
        result = self.last_whatsapp_result
        if result is None or not result.captured_attachments:
            messagebox.showwarning("Fotos necessárias", "Ainda não há fotos copiadas para analisar.")
            return
        self.review_button.configure(state="disabled")
        self.status_var.set("Lendo etiquetas para revisão…")
        self._set_status("warning")
        worker = threading.Thread(target=self._run_photo_review, args=(result,), daemon=True)
        worker.start()

    def _run_photo_review(self, result: WhatsAppProbeResult) -> None:
        def progress(current: int, total: int, filename: str) -> None:
            self.after(0, lambda: self._set_details([
                f"• Foto {current} de {total}",
                f"• Arquivo: {filename}",
                "• A leitura é local e não altera o WhatsApp nem a planilha.",
            ]))

        drafts = build_review_drafts(result, progress)
        self.after(0, lambda: self._show_photo_review(drafts))

    def _show_photo_review(self, drafts: list[LabelDraft]) -> None:
        self.status_var.set("Área temporária pronta para revisão")
        self._set_status("success")
        self.review_button.configure(state="normal", text="Reabrir revisão temporária")
        script = Path(__file__).resolve().parents[1] / "scripts" / "render_current_html_review.py"
        try:
            python_exec = Path(sys.executable)
            if python_exec.name.lower() == "pythonw.exe":
                python_exec = python_exec.with_name("python.exe")
            completed = subprocess.run(
                [str(python_exec), str(script)], capture_output=True, text=True,
                encoding="utf-8", errors="replace", timeout=30,
                creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0), check=True,
            )
            output = Path(completed.stdout.strip().splitlines()[-1])
            if output.exists():
                self.review_html_path = output
                os.startfile(str(output))
                self.review_button.configure(state="normal", text="Reabrir revisão HTML")
                self._set_details([
                    "Revisão HTML criada no mesmo fluxo do aplicativo.",
                    f"Arquivo: {output}",
                    "",
                    "Revise as pendentes no navegador. Nenhum dado foi escrito na planilha.",
                ])
                return
        except (OSError, subprocess.SubprocessError, IndexError) as exc:
            self._set_details([f"Não foi possível abrir a revisão HTML: {exc}"])
        # Do not reopen the legacy table window: the agreed review format is
        # the HTML card view. The error remains visible in the main app.
        self.review_button.configure(state="normal")

    def _test_stake_entry(self) -> None:
        try:
            entry = parse_stake_text(self.stake_input_var.get())
            self.stake_result_var.set(
                f"ESTACA • Peça {entry.piece} • {entry.multiplier} × "
                f"{entry.base_value} = Quantidade {entry.quantity:,}".replace(",", ".")
                + " • Dimensões e volume unitário vazios"
            )
        except ValueError as exc:
            self.stake_result_var.set(str(exc))

    def _set_status(self, status: str) -> None:
        schemes = {
            "success": (COLORS["light_green"], COLORS["green"]),
            "warning": (COLORS["light_amber"], COLORS["amber"]),
            "error": (COLORS["light_red"], COLORS["red"]),
        }
        bg, fg = schemes[status]
        self.status_banner.configure(bg=bg, fg=fg)

    def _set_details(self, lines: list[str]) -> None:
        self.details_text.configure(state="normal")
        self.details_text.delete("1.0", "end")
        self.details_text.insert("1.0", "\n".join(lines))
        self.details_text.configure(state="disabled")


class ReviewWindow(tk.Toplevel):
    COLUMNS = ("status", "data", "tipo", "obra", "peca", "dimensoes", "volume")

    def __init__(self, parent: tk.Widget, drafts: list[LabelDraft], workbook_path: str, period: PeriodSelection) -> None:
        super().__init__(parent)
        self.title("Revisão temporária — Fechamento WL")
        self.geometry("1180x560+55+45")
        self.minsize(900, 430)
        self.drafts = drafts
        self.workbook_path = workbook_path
        self.period = period

        tk.Label(
            self,
            text="Revisão temporária das etiquetas",
            font=("Segoe UI", 17, "bold"),
            fg=COLORS["navy"],
        ).pack(anchor="w", padx=18, pady=(15, 2))
        tk.Label(
            self,
            text="Aprove, edite ou rejeite. Nada será enviado à planilha nesta tela.",
            font=("Segoe UI", 10),
            fg=COLORS["muted"],
        ).pack(anchor="w", padx=18, pady=(0, 10))

        frame = tk.Frame(self)
        frame.pack(fill="both", expand=True, padx=18)
        self.tree = ttk.Treeview(frame, columns=self.COLUMNS, show="headings", selectmode="browse")
        headings = {
            "status": "Situação", "data": "Data", "tipo": "Tipo", "obra": "Obra",
            "peca": "Peça", "dimensoes": "Dimensões", "volume": "Vol. unit.",
        }
        widths = {"status": 145, "data": 90, "tipo": 150, "obra": 220, "peca": 90, "dimensoes": 180, "volume": 85}
        for column in self.COLUMNS:
            self.tree.heading(column, text=headings[column])
            self.tree.column(column, width=widths[column], minwidth=65)
        scrollbar = ttk.Scrollbar(frame, orient="vertical", command=self.tree.yview)
        self.tree.configure(yscrollcommand=scrollbar.set)
        self.tree.pack(side="left", fill="both", expand=True)
        scrollbar.pack(side="right", fill="y")
        self.tree.bind("<Double-1>", lambda _event: self._edit_selected())

        actions = tk.Frame(self)
        actions.pack(fill="x", padx=18, pady=14)
        ttk.Button(actions, text="Aprovar", style="Primary.TButton", command=self._approve_selected).pack(side="left")
        ttk.Button(actions, text="Editar", style="Secondary.TButton", command=self._edit_selected).pack(side="left", padx=8)
        ttk.Button(actions, text="Rejeitar", style="Secondary.TButton", command=self._reject_selected).pack(side="left")
        ttk.Button(actions, text="Consolidar aprovados", style="Primary.TButton", command=self._show_consolidated).pack(side="left", padx=18)
        ttk.Button(actions, text="Fechar", style="Secondary.TButton", command=self.destroy).pack(side="right")
        self._refresh()

    def _refresh(self) -> None:
        selected = self.tree.selection()
        self.tree.delete(*self.tree.get_children())
        for index, draft in enumerate(self.drafts):
            volume = "" if draft.unit_volume is None else str(draft.unit_volume).replace(".", ",")
            self.tree.insert("", "end", iid=str(index), values=(
                draft.status, draft.message_date, draft.type_name, draft.work,
                draft.piece, draft.dimensions, volume,
            ))
        if selected and self.tree.exists(selected[0]):
            self.tree.selection_set(selected[0])

    def _selected(self) -> LabelDraft | None:
        selection = self.tree.selection()
        if not selection:
            messagebox.showinfo("Selecione uma linha", "Selecione primeiro a etiqueta que deseja revisar.", parent=self)
            return None
        return self.drafts[int(selection[0])]

    def _approve_selected(self) -> None:
        draft = self._selected()
        if draft is None:
            return
        if draft.warnings:
            messagebox.showwarning(
                "Há campos para confirmar",
                "Edite os campos indicados antes de aprovar:\n\n" + "\n".join(draft.warnings),
                parent=self,
            )
            return
        draft.status = "APROVADO"
        self._refresh()

    def _reject_selected(self) -> None:
        draft = self._selected()
        if draft is None:
            return
        draft.status = "REJEITADO"
        self._refresh()

    def _edit_selected(self) -> None:
        draft = self._selected()
        if draft is None:
            return
        editor = tk.Toplevel(self)
        editor.title("Editar dados da etiqueta")
        editor.transient(self)
        editor.grab_set()
        fields = (
            ("Data", "message_date"), ("Tipo", "type_name"), ("Obra", "work"),
            ("Produto", "product"), ("Peça", "piece"), ("Dimensões", "dimensions"),
            ("Volume unitário", "unit_volume"),
        )
        variables: dict[str, tk.StringVar] = {}
        for row, (label, attribute) in enumerate(fields):
            tk.Label(editor, text=label, font=("Segoe UI", 9, "bold")).grid(row=row, column=0, sticky="w", padx=14, pady=6)
            value = getattr(draft, attribute)
            variables[attribute] = tk.StringVar(value="" if value is None else str(value).replace(".", ","))
            tk.Entry(editor, textvariable=variables[attribute], width=55).grid(row=row, column=1, padx=14, pady=6)

        def save() -> None:
            volume_text = variables["unit_volume"].get().strip()
            try:
                volume = float(volume_text.replace(",", ".")) if volume_text else None
            except ValueError:
                messagebox.showwarning("Volume inválido", "Informe o volume com números e vírgula.", parent=editor)
                return
            for attribute in ("message_date", "type_name", "work", "product", "piece", "dimensions"):
                setattr(draft, attribute, variables[attribute].get().strip())
            draft.unit_volume = volume
            required = (draft.message_date, draft.type_name, draft.work, draft.piece, draft.dimensions, draft.unit_volume)
            draft.warnings = [] if all(value not in ("", None) for value in required) else ["Ainda há campos obrigatórios vazios"]
            draft.status = "PRONTO PARA REVISÃO" if not draft.warnings else "CONFIRMAR"
            editor.destroy()
            self._refresh()

        ttk.Button(editor, text="Salvar correção", style="Primary.TButton", command=save).grid(row=len(fields), column=1, sticky="e", padx=14, pady=14)

    def _show_consolidated(self) -> None:
        rows = group_approved_drafts(self.drafts)
        if not rows:
            messagebox.showinfo(
                "Nenhuma linha aprovada",
                "Aprove pelo menos uma etiqueta antes de consolidar.",
                parent=self,
            )
            return
        ConsolidatedWindow(self, rows, self.workbook_path, self.period)


class ConsolidatedWindow(tk.Toplevel):
    def __init__(self, parent: tk.Widget, rows: list[ConsolidatedRow], workbook_path: str, period: PeriodSelection) -> None:
        super().__init__(parent)
        self.title("Resumo consolidado — ainda não enviado ao Excel")
        self.geometry("1120x500+75+65")
        self.rows = rows
        self.workbook_path = workbook_path
        self.period = period
        tk.Label(
            self,
            text="Resumo das linhas aprovadas",
            font=("Segoe UI", 16, "bold"),
            fg=COLORS["navy"],
        ).pack(anchor="w", padx=18, pady=(15, 2))
        tk.Label(
            self,
            text=(
                f"{sum(row.source_count for row in rows)} etiquetas aprovadas → "
                f"{len(rows)} linhas. Mesmo dia e todos os campos iguais foram unidos."
            ),
            fg=COLORS["muted"],
        ).pack(anchor="w", padx=18, pady=(0, 10))
        columns = ("data", "tipo", "obra", "quantidade", "peca", "dimensoes", "volume", "carga")
        tree = ttk.Treeview(self, columns=columns, show="headings")
        titles = {
            "data": "Data", "tipo": "Tipo", "obra": "Obra", "quantidade": "Quantidade",
            "peca": "Peça", "dimensoes": "Dimensões", "volume": "Vol. unit.", "carga": "Tipo de carga",
        }
        widths = {"data": 90, "tipo": 155, "obra": 210, "quantidade": 85, "peca": 80, "dimensoes": 170, "volume": 85, "carga": 135}
        for column in columns:
            tree.heading(column, text=titles[column])
            tree.column(column, width=widths[column], minwidth=65)
        for row in rows:
            volume = "" if row.unit_volume is None else str(row.unit_volume).replace(".", ",")
            tree.insert("", "end", values=(
                row.message_date, row.type_name, row.work, row.quantity,
                row.piece, row.dimensions, volume, row.cargo_type,
            ))
        tree.pack(fill="both", expand=True, padx=18)
        tk.Label(
            self,
            text="Volume total, unidade de medida, valor unitário e valor total continuam sob responsabilidade das fórmulas da planilha.",
            fg=COLORS["amber"],
            font=("Segoe UI", 9, "bold"),
        ).pack(anchor="w", padx=18, pady=10)
        actions = tk.Frame(self)
        actions.pack(fill="x", padx=18, pady=(0, 14))
        self.import_button = ttk.Button(
            actions,
            text="Importar aprovados na planilha selecionada",
            style="Primary.TButton",
            command=self._confirm_import,
        )
        self.import_button.pack(side="left")
        ttk.Button(actions, text="Fechar", style="Secondary.TButton", command=self.destroy).pack(side="right")

    def _confirm_import(self) -> None:
        confirmed = messagebox.askyesno(
            "Confirmar importação",
            f"Será criado um backup e {len(self.rows)} linha(s) serão incluídas em:\n\n"
            f"{self.workbook_path}\n\nApenas os campos de origem serão preenchidos. Continuar?",
            parent=self,
        )
        if not confirmed:
            return
        self.import_button.configure(state="disabled", text="Criando backup e importando…")
        threading.Thread(target=self._run_import, daemon=True).start()

    def _run_import(self) -> None:
        try:
            result = write_approved_rows(self.workbook_path, self.period, self.rows)
        except Exception as exc:
            message = str(exc)
            self.after(0, lambda: self._import_error(message))
            return
        self.after(0, lambda: self._import_success(result))

    def _import_error(self, message: str) -> None:
        self.import_button.configure(state="normal", text="Tentar importar novamente")
        messagebox.showerror("Importação não concluída", message, parent=self)

    def _import_success(self, result) -> None:
        self.import_button.configure(state="disabled", text="Importação concluída")
        messagebox.showinfo(
            "Importação concluída",
            "As linhas aprovadas foram incluídas.\n\n"
            f"Linhas: {', '.join(str(row) for row in result.imported_rows)}\n"
            f"Backup: {result.backup_path}",
            parent=self,
        )


def run() -> None:
    app = FechamentoApp()
    app.mainloop()
